image:
  repository: bitnamilegacy/mysql
  tag: 9.4

architecture: replication
auth:
  rootPassword: secret
  username: java
  password: java-pass
  database: java-db

primary:
  persistence:
    enabled: true
    size: "8Gi"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "768Mi"
      cpu: "500m"

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    size: "8Gi"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "768Mi"
      cpu: "500m"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring-stack
  image:
    tag: latest
