apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-auth
  namespace: monitoring
data:
  slack-url: <YOUR_TOKEN>

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gmail-auth
  namespace: monitoring
data:
  password: <PWD>
