apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: stateful-set-rule
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring-stack
spec:
  groups:
    - name: stateful-set.rules
      rules:
      - alert: StatefulSetReplicasMismatch
        expr: kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas_current != 1
        for: 1m
        labels:
          severity: critical
          namespace: monitoring
        annotations:
          summary: "StatefulSet {{ $labels.statefulset }} is down (instance {{ $labels.instance }})"
          description: "A StatefulSet {{ $labels.statefulset }} went down\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
